#### 体系结构
   ```java
   java.lang.Object
      |----java.lang.Throwable
         |-------java.lang.Error：错误，java程序对此无能为力，不显式的处理
         |-------java.lang.Exception:异常。需要进行处理
            |------RuntimeException:运行时异常
               |-----ArrayIndexOutOfBoundsException/NullPointerException/ArithmeticException/ClassCastException
            |------非RuntimeException:编译时异常   
   ```
#### 如何处理异常
   - java 中的“抓抛模型”
      - "抛"：当我们执行代码时，一旦出现异常，就会在异常的代码处生成一个对应的异常类型的对象，并将此对象抛出。(自动抛出/手动抛出)一旦抛出此异常类的对象，那么程序就终止执行此异常类的对象抛给方法的调用者。
      - "抓"：抓住上一步抛出来的异常类的对象。如何抓？即为异常处理的方式
         ```java
         //处理方法1
          try{
          //可能出现异常的代码
          }catch(Exception1 e1){
          //处理的方式1
          }catch(Exception2 e2){
          //处理的方式2
          }finally{
          //一定要执行的代码 
          }
  
          //处理方法2
          //在方法的声明处，显式的使用throws + 异常类型
          public void method1()  throws Exception1 e1,Exception2 e2{
            //可能出现异常（尤其是编译时异常，一定要处理）
          }
         ```
          - try内声明的变量，类似于局部变量，出了try{}语句，就不能被调用
          - finally是可选的
          - catch语句内部是对异常对象的处理：getMessage();  printStackTrace();
          - 可以有多个catch语句，try中抛出的异常类对象从上往下去匹配catch中的异常类的类型，一旦满足就执行catch中的代码。执行完，就跳出其后的多条catch语句
          - 如果异常处理了，那么其后的代码继续执行。
          - 若catch中多个异常类型是"并列"关系，孰上孰下都可以。若catch中多个异常类型是"包含"关系，须将子类放在父类的上面，进行处理。否则报错！
          - finally中存放的是一定会被执行的代码，不管try中、catch中是否仍有异常未被处理，以及是否有return语句。
          - try-catch是可以嵌套的。
#### 如何手动抛出一个异常
   - 在方法的内部，可以使用  throw + 异常类对象，来手动的抛出一个异常！
#### 如何自定义一个异常类
   ```java
    //1.自定义的异常类继承现有的异常类
    //2.提供一个序列号，提供几个重载的构造器
    public class MyException extends Exception{
        
        static final long serialVersionUID = -70348975766939L;
        
        public MyException(){
            
        }
        public MyException(String msg){
            super(msg);
        }
    }
   ```
#### throw与throws的区别
   - throw语句用在方法体内，表示抛出异常，由方法体内的语句处理。
   - throws语句用在方法声明后面，表示再抛出异常，由该方法的调用者来处理。
 